site_name: CarRent

theme:
  name: material

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true  
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  